### ISSUE TITLE
Vector test failures

### ISSUE THREAD

**Issue by spencergilbert** [prometheus/compliance#34]
I started looking into the failures for Vector in my spare time and already found some things (planning on making a PR to resolve anything on this end when I have enough fixes in place).

Some of the errors (ex: missing headers) appear to be on the configuration side for Vector, updating https://github.com/prometheus/compliance/blob/main/remote_write/targets/vector.go#L38 to either have `/push` or `/api/v1/write` both seem to resolve the missing headers portion of the test - though I'm not sure why both paths work.

The `Headers` test still fails with this change with `found zero samples for {__name__="now"}` - however, if I update the Vector config to be:

```toml
[sources.prometheus_scrape]
  type = "prometheus_scrape"
  endpoints = ["http://%s/metrics"]
  scrape_interval_secs = 1

[sinks.prometheus_remote_write]
  type = "prometheus_remote_write"
  inputs = ["prometheus_scrape"]
  endpoint = "%s/api/v1/write"

[sinks.prometheus]
  type = "prometheus_remote_write"
  inputs = ["prometheus_scrape"]
  endpoint = "http://127.0.0.1:9090/api/v1/write"
```

And run prometheus locally:

```bash
docker run --rm -it -p 9090:9090 prom/prometheus --config.file=/etc/prometheus/prometheus.yml --enable-feature=remote-write-receiver
```

I am getting a result back when querying for `{__name__="now"}` - It's not immediately clear to me the difference between the test setup and the experimental implementation and can dig in more if y'all don't have a reason off the top of your head.

I'll keep working on the test setup (and any required changes on the Vector side) and update in this issue or on a draft PR, depending on your preference.
