### ISSUE TITLE
[alert generator] question about `alertname` label

### ISSUE THREAD

**Issue by hagen1778** [prometheus/compliance#80]
The [spec](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#step-3) says the following:
```
The alert name from the alerting rule (HighRequestLatency from the example above) MUST be added to the labels of the alert with the label name as alertname. It MUST override any existing alertname label.
```

The statement above says that rule's name should override any existing `alertname` label. Does it mean that in templates `$labels.alertname` and `.Labels.alertname` values should behave in the same way? 
One of the testcases expects template value to be equal to the existing `alertname` label:
https://github.com/prometheus/compliance/blob/c7c726de89973d77cb491faa1b32cfddf7dcde8a/alert_generator/cases/case_new_alerts_and_order_check.go#L254
But this looks controversial to what spec says.

**Comment by codesome** [comment]
The [step 2 of processing instant query result](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#step-2) says this:

> The labels and annotation templates from the alerting rule MUST be run for each of these alerts individually **with label-value data for the template coming from the corresponding element from the result vector**.

The `alertname` is added _after_ the template execution and overrides everything (which is [step 3](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#step-3)). While for the template execution step itself, it gets the label data from the queried samples.

Does that clarify your doubt?

**Comment by hagen1778** [comment]
It does. Thanks!

However, looking at the Prometheus code the templating for labels and annotations is happening with different label sets:
https://github.com/prometheus/prometheus/blob/2c1be4df7bb50eec068a7432c041bab900fdede1/rules/alerting.go#L388-L396

Labels are templated before the `alertname` override. And annotations are templated after the override.
This also can be tested via the following ruleset:
```
rules:
        - alert: AlwaysFiring
          expr: 'up'
          for: 1m
          labels:
            foo: bar
          annotations:
            description: This should produce more alerts later
        - alert: NewAlerts_OrderCheck_Rule2
          expr: ALERTS{alertstate="firing", alertname="AlwaysFiring", foo="bar"}
          labels:
            foo: baz
            prevAlertname: '{{$labels.alertname}}'
          annotations:
            description: Based on ALERTS. Old alertname was {{$labels.alertname}}. foo was {{.Labels.foo}}.
```

After `AlwaysFiring` fires, the `NewAlerts_OrderCheck_Rule2` alert will be displayed as following:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/2902918/160810551-05841cdc-b4dc-45fb-aa64-402b795f80cd.png">

`prevAlertname` will indeed contain the name of `AlwaysFiring` alert. But annotation will contain the current rule's name. It is also proven by what Alertmanager receives:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2902918/160810794-1a00bd02-ee67-4102-a411-7e5130537051.png">


Is this behaviour expected? Does it reflect the current spec?
Sorry if I missed the obvious thing.
